### ISSUE TITLE
conductor not calculating time between steps correctly

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#64]
Conductor is not calculating time correctly again.  This incorrect information is going to the metrics section
EX:
Furnish/install Pvc Swimming Pool Liners spec 7020

Contract Sent to vendor 2/22
Contract Received from vendor 3/8

says it took 0 hours to finish.

**Comment by bsmithgall** [comment]
Are there many examples of this or just one?

**Comment by bsmithgall** [comment]
Looking at the database these have duplicate entered and exited times so
the time calculation is correct.

**Comment by rileystewart** [comment]
what do you mean duplicate entered and exited times?  It shows that the contract was sent on 2/22 and that it was received on 3/8.  That is 15 days not 0 hours.

**Comment by bsmithgall** [comment]
Ah I see now.

This should be fixed.

**Comment by rileystewart** [comment]
This is happening w/ the insurance one too....I don't know how many this potentially happened w/ in the past...

**Comment by rileystewart** [comment]
Same w/ jersey barriers

**Comment by rileystewart** [comment]
Repairs to salt spreader has incorrect calculation too but not 0 (time between received from vendor and county contract complete says 6 days but its 7.)

**Comment by bsmithgall** [comment]
Something more systemic is going on, I'll investigate this weekend.

**Comment by bsmithgall** [comment]
Here is what I suspect is happening:
1. A user marks several steps in conductor, each, say 10 days apart. So, step one is marked complete January 1, step two is marked January 10, and step three is marked January 20.
2. A user reverts from step three to step two with the date box saying January 15.
3. The user marks it complete on January 20.

After this set of operations, the stages are set out as follows:

| Stage | Enter | Exit |
| --- | --- | --- |
| Stage 1 | January 1 | January 10 |
| Stage 2 | January 15 | January 20 |
| Stage 3 | January 20 | n/a |

So the question is, how should Conductor handle this case? Which is correct, the stage 1 exit date, or the stage 2 enter time? I think in the future, one of these should be considered _correct_ but I think it's a domain question as to which one. If you can answer this question, I can create and release a solution. I can also write a script to go over all of the historical contracts and apply whatever logic you think is correct to them.

Let me know @rileystewart

**Comment by rileystewart** [comment]
The enter date of one step is always the ending date of the previous step. There should never be any gaps in time between steps. 

Riley R. Stewart

**Comment by bsmithgall** [comment]
Just to be clear, in this case, Conductor should automatically move the stage 2 start date to January 10?

**Comment by rileystewart** [comment]
Correct. If a step is reverted for some reason. The new day that step is completed is the next steps start date

Riley R. Stewart

**Comment by bsmithgall** [comment]
Right. The question I am asking is about the step _before_ the reversion -- step one in the example is above, while you are answering about the step after.

**Comment by bsmithgall** [comment]
I've submitted a patch in #65 with the logic in the commit message, and I wanted to copy that here so that you can understand what is going on:

---

When transitioning forward, if the stage that we are exiting's enter time does not match the previous stage's enter time, automatically adjust it to make them match. This can happen if, for example, the following steps are taken:
1. A user marks several steps in conductor, each, say 10 days apart. So, step one is marked complete January 1, step two is marked January 10, and step three is marked January 20.
2. A user reverts from step three to step two with the date box saying January 15.
3. The user marks step 2 complete complete on January 16.

When these steps occur in sequence, a gap of five days appears between step one and step two. This commit will automatically mark the step two enter date to be equal to the step one exit date.

The reason that we don't handle this on the revert side is because you can "revert to" a certain time right now, which leads to a common user behavior of reverting to the time you want to mark the step as complete and then immediately marking it as complete, or marking it as complete one day later. The path of least surprise in this case is to continue to allow the user to do this but to automatically back-adjust the reverted date instead of having him or her choose a date in the past and then find that conductor has reverted them to a different date altogether!

---

I've also written a script that we can run that will back-fix all problems that currently exist.

**Comment by bsmithgall** [comment]
Am I OK to merge this change? It might also address what is happening with #66
