### ISSUE TITLE
beacon documents not working

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#7]
We are finally in the position where we are starting to develop documents that can be checked for beacon opportunities.  I found 2 different issues.
1. When we check a box of one of the documents, it changes nothing in the opportunity.  It should display that the document is needed.
2. If we go to try to add a document that they need for an opportunity, I go to Beacon>Admin>Beacon>Documents>Create.  Once there, there is not a 'Browse' option for me to be able to add a document.

**Comment by bsmithgall** [comment]
Are you talking about the documents the vendor needs?

For 2) you can go here: https://www.buildpgh.com/admin/bid_document/

I'll look into 1) today

**Comment by rileystewart** [comment]
When I go there and hit create
Display name, description, and form here all are just text boxes for me to fill in

**Comment by bsmithgall** [comment]
Yes, that's the extent of where we got to with that feature.

**Comment by rileystewart** [comment]
okay so the documents feature can't be used?   I guess I'm confused as to why there's a documents section if there isn't the option to upload the documents.   

This is the first time I've ever went into this area so it is the first I am seeing it and not sure I understand

**Comment by bsmithgall** [comment]
There are two forms of documents:

**Vendor Documents Needed** are documents that the vendor will need to provide in order to bid on the contract (this can include certificates of insurance, bid bonds etc). Typically, you wouldn't need to actually upload anything in this section, it's just an indication that the RFP/bid document mentions that this is a requirement that the vendor will have.

**Bid Documents** on the other hand are the documents that you are providing to the vendor. The section for these is underneath the documents that the vendor will need to provide back to you. This section is for RFP/IFB documents, Q&A documents, addendum, etc.

This should all be covered in the Beacon user guide if I'm not mistaken.
