### ISSUE TITLE
status of contracts in 'download all' contracts

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#80]
The status's of contracts in the download all option of conductor is still very confusing and at times inaccurate.  

For example: plotter material.  There are multiple when I download this option...one showing a status 'not started' and one showing 'started'.  The problem is the one that shows 'started' is the most recent but it is not in progress but is in the 'all contracts' list.  I want this download to be able to tell me removed from conductor, in progress, and in the list of all contracts in conductor.  There should only be 3 statuses and they should reflect where the contract is.

**Comment by bsmithgall** [comment]
Can you provide item number(s) for the contracts in question? You should also be able to upload the file you are looking at as well so that I can be sure we are looking at the same thing.

**Comment by rileystewart** [comment]
[sheet for ben.xlsx](https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/files/332319/sheet.for.ben.xlsx)

**Comment by bsmithgall** [comment]
So for plotters we have the following situation:
1. There is one that is properly listed as "removed from conductor"
2. There is a parent contract that is expired (item #2506), which is displaying as "not started" -- this is _technically_ true because that particular contract itself wasn't started, but its child (item #4069) was indeed started. This contract was not marked as "archived" when its child was complete. If you go to the contract's [Scout admin page](https://procurement.pittsburghpa.gov/admin/contract/edit/?id=2506) and mark it as "Archived" it should properly show up as "completed" in the download.
3. There is a child contract (item #4069), which has gone through all of the steps for renewal and should be marked as completed. 

I can understand how this can be confusing, so I'm going to submit a patch that provides a number of fixes and improvements to the query, including ensuring that all contracts that are in the conductor list are noted as such. I'm also going to provide some clarity into whether a contract has been (i.e. it is in the final stage of its flow _and_ it has an expiration date) vs. whether it is just in progress.

I'll deploy this fix today and it should work immediately. Let me know if there are problems.

**Comment by rileystewart** [comment]
I am even more confused by the status's now.  I only need 3.  

Removed from conductor
In Progress
Not Started

If a contract is completed in conductor, I don't need that to show up in this list as 'completed'.  I need the new information to show up as 'Not Started' with the new expiration date. 

I should only have one of every single contract (if I remove 'removed from conductor' contracts).  This number should be the exact same as when I add the number of in progress/not started contracts in Conductor.

**Comment by bsmithgall** [comment]
When we originally talked about this many months ago a key requirement was the ability to trace a contract's lineage (e.g. you should be able to to look at a contract and see where it came from, going back as far as is it). Is this no longer true?

I think that it's very important that you have more information than you want in a "download all" feature -- it's always easier to cut out information (via excel filters, for example) than to add it back in.

**Comment by rileystewart** [comment]
I don't think that we need contract lineage for anything.  As long as the information (like department/agent) goes from the old to the new when its created.

Before this change is made though, how many hours would it take?

**Comment by bsmithgall** [comment]
I would prefer not to make it, but I imagine that it would take 1-2 hours.
