### ISSUE TITLE
download raw data has incorrect info/order

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#82]
I did the download raw data for the contract type 'city county formal bidding' and am perplexed by what came back.  
- Department Review Sent column is in the middle when it should be the first step
- There are contracts like 'Extermination', 'Hazardous Material Cleanup', 'Grass Seed', etc that have dates in columns that have not happened yet (for these 3 they have dates in contract sent to vendor yet it has never been sent to the vendor). 

[city-county download raw data.xlsx](https://github.com/CityofPittsburgh/pittsburgh-purchasing-suite/files/334732/city-county.download.raw.data.xlsx)
 I'm not sure how many of the downloads have this problem, but I need these dates to be accurate and reflect what time they were actually finished in conductor.

**Comment by bsmithgall** [comment]
I will take a look at this later today if I can, or failing that this week.

**Comment by bsmithgall** [comment]
This was due to an unexpected bug that arose from certain transition times having microseconds in their timestamps while others did not. This led to a situation where the ordering column that I was using was thrown out of whack. I've switched up the way I'm ordering data and have tested it to make sure that it is right. The problem should be fixed once #83 is deployed later tonight and should be available as soon as the deploy happens.
