### ISSUE TITLE
WHOLE SYSTEM DOWN

### ISSUE THREAD

**Issue by rileystewart** [CityofPittsburgh/pittsburgh-purchasing-suite#93]
Ben,  I can't get into any website without an error (beacon, scout or conductor).

Need to know if this is a problem you need to fix or that is an issue with I&P.

**Comment by rileystewart** [comment]
BACK UP.

**Comment by bsmithgall** [comment]
Sorry I sent an email response that didn't seem to make it here:

This is part of a greater internet wide problem with a DNS provider: https://www.dynstatus.com/incidents/nlr4yrr162t8

This issue is affecting Twitter, Spotify, Github, Airbnb, and heroku, our provider. Unfortunately there isn't a whole lot that can be done while the outage is occurring.

I think access will be intermittent until the situation fully resolves.

**Comment by bsmithgall** [comment]
It will likely be intermittently available until the larger issue is
resolved.

**Comment by bsmithgall** [comment]
This is part of a greater internet wide problem with a DNS provider:
https://www.dynstatus.com/incidents/nlr4yrr162t8

This issue is affecting Twitter, Spotify, Github, Airbnb, and heroku, our
provider. Unfortunately there isn't a whole lot that can be done while the
outage is occurring.
